config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  get 'auth/github', as: 'github_login'
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/dashboard', to: 'dashboard#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  def self.find_or_create_from_auth_hash(auth_hash)
    User.find_or_create_by(uid: auth_hash['uid'])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def show
    @public_repos = RepoFacade.public_repos(current_user)
    @private_repos = RepoFacade.private_repos(current_user)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: :create

  def create
    user = SessionFacade.session_details(auth_hash)
    session[:user_id] = user.id
    redirect_to dashboard_path
  end

  protected

  def auth_hash
    request.env['omniauth.auth']
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/show.html.erb
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col col-md-12">
      <h1 class="center">Welcome, <%= current_user.username %></h1>
    </div>
  </div>
</div>

<div class="container">
  <div class="row d-flex">
    <div class="col group-card">
      <h3 class='fas fa-lock-open'> <strong>Your Public Repos</strong></h3>
      <p>
        <% @public_repos.each do |repo| %>
          <li> <%= link_to repo.name, repo.url %> </li>
        <% end %>
      </p>
    </div>
    <div class="col group-card">
      <h3 class='fas fa-lock'>  <strong>Your Private Repos</strong></h3>
      <p>
        <% @private_repos.each do |repo| %>
          <li> <%= link_to repo.name, repo.url %> </li>
        <% end %>
      </p>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col col-md-12">
      <h1 class="center">Welcome!</h1>
    </div>
    <div class="col col-md-12 center">
      <p>To discover all of the repos, both public and private, that you have please click login.</p>
      <p>You will be authenticated via GitHub and taken to your dashboard.</p>
      <p>There you will see lists of your private and public repos.</p>
    </div>
    <div class="col col-md-2 login-card center">
      <%= link_to "Login", github_login_path %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OmniauthProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <script src='https://kit.fontawesome.com/a076d05399.js'></script>

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Bungee+Shade&family=Philosopher&family=Redressed&display=swap" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="image-wrapper">
        <img src="https://images.unsplash.com/photo-1500964757637-c85e8a162699?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1378&q=80" alt="">
      </div>
    <%= yield %>
  </body>
  <a class="accredidation" style="background-color:LigthGray;color:black;text-decoration:none;padding:4px 6px;font-family:-apple-system, BlinkMacSystemFont, &quot;San Francisco&quot;, &quot;Helvetica Neue&quot;, Helvetica, Ubuntu, Roboto, Noto, &quot;Segoe UI&quot;, Arial, sans-serif;font-size:12px;font-weight:bold;line-height:1.2;display:inline-block;border-radius:3px" href="https://unsplash.com/@8moments?utm_medium=referral&amp;utm_campaign=photographer-credit&amp;utm_content=creditBadge" target="_blank" rel="noopener noreferrer" title="Download free do whatever you want high-resolution photos from Simon Matzinger"><span style="display:inline-block;padding:2px 3px"><svg xmlns="http://www.w3.org/2000/svg" style="height:12px;width:auto;position:relative;vertical-align:middle;top:-2px;fill:white" viewBox="0 0 32 32"><title>unsplash-logo</title><path d="M10 9V0h12v9H10zm12 5h10v18H0V14h10v9h12v-9z"></path></svg></span><span style="display:inline-block;padding:2px 3px">Photo Credit to Simon Matzinger</span></a>
</html>